workflows:
  ios-sdk-build:
    name: Alps iOS SDK Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      xcode: latest
    scripts:
      - name: Generate Xcode Project
        script: |
          swift package generate-xcodeproj
      - name: Build Example App Archive
        script: |
          xcodebuild archive \
            -project AlpsSDK.xcodeproj \
            -scheme AlpsSDKExample \
            -configuration Release \
            -archivePath build/Alps.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/Alps.xcarchive \
            -exportOptionsPlist Example/ExportOptions.plist \
            -exportPath build/ipa
    artifacts:
      - build/ipa/**/*.ipa
