name: AlpsSDKExample
settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

packages:
  PusherSwift:
    url: https://github.com/pusher/pusher-websocket-swift
    from: 10.1.5

targets:
  AlpsSDK:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources/AlpsSDK
        excludes:
          - Info.plist
    resources:
      - path: Sources/AlpsSDK/Info.plist
    dependencies:
      - package: PusherSwift
    settings:
      BUNDLE_IDENTIFIER: com.tryalps.sdk
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"
      INFOPLIST_FILE: Sources/AlpsSDK/Info.plist

  AlpsSDKExample:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Example/AlpsSDKExample
    resources:
      - path: Example/AlpsSDKExample
    dependencies:
      - target: AlpsSDK
    settings:
      BUNDLE_IDENTIFIER: com.tryalps.sdk.example
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: "NO"
      CODE_SIGN_STYLE: Automatic
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"

schemes:
  AlpsSDKExample:
    build:
      targets:
        AlpsSDKExample: all
    archive:
      config: Release
